version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tools/local-ui/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      vite-and-tools:
        patterns:
          - "vite*"
          - "esbuild*"
          - "@vitejs/*"

  - package-ecosystem: "pip"
    directory: "/tools/local-ui/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      fastapi-stack:
        patterns:
          - "fastapi*"
          - "starlette*"
          - "uvicorn*"
          - "pydantic*"
