Narrative:   ['(?i)\b(scene|dialog|story|narrative|script)\b']
QA & UX:     ['(?i)\b(qa|regression|usability|ux|accessibility)\b']
A&R:         ['(?i)\b(authenticity|citation|source|verify|research)\b']
Steam Ops:   ['(?i)\b(steam|depot|branch|app id|store page)\b']
Builds:      ['(?i)\b(build|ci|unity|unreal|packaging|artifact)\b']
Mail:        ['(?i)\b(stand-?by|handoff|postmaster|decision)\b']
Docs:        ['(?i)\b(readme|docs?|documentation|mkdocs)\b']
enable-versioned-regex: true
