name: Build Windows bundle

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r backend/requirements.lock
          pip install pyinstaller pytest pytest-cov
      - name: Run tests
        run: |
          pytest -q --junitxml=test-results.xml --cov=tools/local-ui/backend --cov-report=xml
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results.xml
            coverage.xml
      - name: Build bundle
        run: python tools/local-ui/build_bundle.py --no-zip
      - name: Smoke test
        run: powershell -ExecutionPolicy Bypass tools/local-ui/smoke.ps1
      - name: Zip bundle
        run: python tools/local-ui/build_bundle.py --zip-only
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daps-windows-bundle
          path: dist/windows/daps_windows_bundle.zip
