name: Build Windows bundle

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/local-ui/backend/requirements.txt
          pip install pyinstaller
      - name: Run backend tests
        run: python -m pytest tools/local-ui/backend/tests
      - name: Build bundle
        run: |
          python tools/local-ui/build_bundle.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daps-windows-bundle
          path: tools/local-ui/dist/daps_bundle.zip
