name: DAPS CI
on:
  pull_request:
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - 'daps/**'
      - '.github/workflows/daps-ci.yml'
  workflow_dispatch: {}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test --if-present
      - name: Smoke route tests
        run: echo "no-op smoke tests (placeholder)"
