name: daps-console
on:
  pull_request: { paths: ['tools/daps-console/**'] }
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: tools/daps-console } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
      - run: npm run build
      - run: npm test --if-present || true
