name: dependency-review

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "tools/local-ui/frontend/**"
      - "tools/local-ui/backend/**"
      - ".github/**"

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: |
            MIT
            BSD-2-Clause
            BSD-3-Clause
            Apache-2.0
            ISC
