# post-process validation report (guarded)
- name: Post-process validation report
  if: always()
  run: |
    set -euo pipefail
    IN=reports/validation-rerun.log
    OUT=reports/validation-clean.log
    # if runner produced a validation report, run postfilter; otherwise create a placeholder
    if [ -f "$IN" ]; then
      python3 .github/scripts/validation_postfilter.py "$IN" "$OUT" 3 || true
    else
      echo "No validation-rerun.log found on runner. Creating placeholder." > "$OUT"
    fi

# upload cleaned validation report (only if present)
- name: Upload cleaned validation report
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: validation-report-clean
    path: |
      reports/validation-clean.log
      reports/*.txt
      artifacts/**
