name: local-ui-pack
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      allow_bypass:
        description: "Allow ci-bypass-localui label to skip UI pack"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

jobs:
  backend-tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      PYTHONPATH: ${{ github.workspace }}/tools/local-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r tools/local-ui/backend/requirements.lock
      - name: Run backend tests
        working-directory: tools/local-ui
        run: pytest -q backend/tests
      - name: Record bypass
        if: ${{ github.event_name == 'pull_request' && inputs.allow_bypass == 'true' && contains(github.event.pull_request.labels.*.name, 'ci-bypass-localui') && (contains(github.event.pull_request.labels.*.name, 'Docs') || contains(github.event.pull_request.labels.*.name, 'docs-only') || contains(github.event.pull_request.labels.*.name, 'Hotfix') || contains(github.event.pull_request.labels.*.name, 'hotfix')) }}
        run: |
          echo "local-ui-pack bypassed by ${{ github.actor }}" >> $env:GITHUB_STEP_SUMMARY
          echo "labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}" >> $env:GITHUB_STEP_SUMMARY
          echo "::warning::local-ui-pack bypassed by ${{ github.actor }}"

  local-ui-build:
    if: ${{ !(github.event_name == 'pull_request' && inputs.allow_bypass == 'true' && contains(github.event.pull_request.labels.*.name, 'ci-bypass-localui') && (contains(github.event.pull_request.labels.*.name, 'Docs') || contains(github.event.pull_request.labels.*.name, 'docs-only') || contains(github.event.pull_request.labels.*.name, 'Hotfix') || contains(github.event.pull_request.labels.*.name, 'hotfix'))) }}
    runs-on: windows-latest
    needs: backend-tests
    defaults:
      run:
        shell: pwsh
    env:
      PYTHONPATH: ${{ github.workspace }}/tools/local-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r tools/local-ui/backend/requirements.lock
      - name: zip pack
        run: |
          mkdir -p dist
          zip -r dist/prompt-hub-v0.3.zip \
            tools/local-ui/backend \
            tools/local-ui/frontend \
            tools/local-ui/run_backend.bat \
            tools/local-ui/run_backend.ps1 \
            tools/local-ui/.env.example \
            tools/local-ui/README.md
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: prompt-hub-v0.3
          path: dist/prompt-hub-v0.3.zip
