name: local-ui
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }

jobs:
  backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: tools/local-ui/backend/requirements.txt
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r tools/local-ui/backend/requirements.txt
          python -m pip install pytest httpx
      - name: Run tests
        env: { PYTHONPATH: tools/local-ui }
        run: python -m pytest tools/local-ui/backend/tests -q

  frontend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: tools/local-ui/frontend/package-lock.json
      - name: Build
        working-directory: tools/local-ui/frontend
        run: |
          npm ci
          npm run build
