name: local-ui-pack
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install backend deps
        run: python -m pip install -U -r tools/local-ui/backend/requirements.txt

      - name: Optional OpenAI mode health
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DAPS_AGENT_MODE: openai
        run: |
          python - <<'PY'
          import importlib.machinery
          from fastapi.testclient import TestClient
          mod = importlib.machinery.SourceFileLoader(
              "daps_main", "tools/local-ui/backend/main.py"
          ).load_module()
          app = getattr(mod, "APP", getattr(mod, "app", None))
          assert app is not None, "APP/app not found"
          c = TestClient(app)
          j = c.get("/health").json()
          print("health:", j)
          PY

      - name: Zip pack
        run: |
          mkdir -p dist
          zip -r dist/prompt-hub-v0.3.zip \
            tools/local-ui/backend \
            tools/local-ui/frontend \
            tools/local-ui/run_backend.bat \
            tools/local-ui/run_backend.ps1 \
            tools/local-ui/.env.example \
            tools/local-ui/README.md

      - uses: actions/upload-artifact@v4
        with:
          name: prompt-hub-v0.3
          path: dist/prompt-hub-v0.3.zip
