name: lock-backend-reqs

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/local-ui/backend/requirements.in'

jobs:
  lock-backend-reqs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install -U pip pip-tools
          pip-compile --generate-hashes tools/local-ui/backend/requirements.in -o tools/local-ui/backend/requirements.lock
