name: Merge patches and trackers

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run merge
        run: |
          python .github/scripts/merge_gdd.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto/merge-patches
          commit-message: "chore: auto-merge patches and trackers"
          title: "Auto-merge: Patches + Trackers → Updated GDD"
          body: |
            This PR auto-applies changes from /Patches and /Trackers, updates section files,
            rebuilds DIPLOMAGIC_GDD_Combined.md, and writes an AUTO_MERGE_REPORT.md and CHANGELOG_AUTO.md.
          delete-branch: true
