name: mkdocs-build

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No mkdocs build configured; passing stub job."
