name: ops-runner
run-name: ops-runner: ${{ inputs.op }} on ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      op:
        description: Select operation
        type: choice
        required: true
        options: [daps-ci, rollover-stamp]
      ref:
        description: Git ref for target workflow
        required: true
        default: main

permissions:
  actions: write
  contents: read

concurrency:
  group: ops-runner-${{ inputs.op }}-${{ inputs.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dispatch daps-ci
        if: ${{ inputs.op == 'daps-ci' }}
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/daps-ci.yml/dispatches" \
            -d "{\"ref\":\"${{ inputs.ref }}\"}"
      - name: Dispatch rollover-stamp
        if: ${{ inputs.op == 'rollover-stamp' }}
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/rollover-stamp.yml/dispatches" \
            -d "{\"ref\":\"${{ inputs.ref }}\"}"
      - name: REPORT
        run: |
          echo "REPORT"
          echo "op=${{ inputs.op }}"
          echo "ref=${{ inputs.ref }}"
          echo "actor=${{ github.actor }}"
          echo "run_id=${{ github.run_id }}"
          python3 - <<'PY'
from datetime import datetime
from zoneinfo import ZoneInfo
print("Timestamp:", datetime.now(ZoneInfo("America/New_York")).strftime("%Y-%m-%d %H%M ET"))
PY
