name: PR Labeler

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR labeler stub; passing."
